-- MySQL Script generated by MySQL Workbench
-- Chủ nhật, 24 Tháng sáu Năm 2018 20:15:02 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema node_tut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema node_tut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `node_tut` DEFAULT CHARACTER SET utf8 ;
USE `node_tut` ;

-- -----------------------------------------------------
-- Table `node_tut`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_tut`.`user` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `node_tut`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_tut`.`device` (
  `id` INT(11) NOT NULL,
  `devicename` VARCHAR(45) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `userID_idx` (`user_id` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`user_id`)
    REFERENCES `node_tut`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
